# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f9cc4336ad87ac06e7d6cb359ed767d411aba2d6af244c30ee8da9b5342142332db9a9674341e4d520fe86a9b52a9ed4f2e51e6e4730ebf0e146a71e9ca3b7

test:
  secret_key_base: 6a79e1940e204ffae93ad689de757ffc80ba67c9eaeb9092feb2f00b0d0a5327206aefc7aa414bb356d93035c9887b30991504245681aeca634b7b5e12a32fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
